service: cis-serverless-backend-actions

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  deploymentBucket: 
  
  environment:
    DYNAMODB_TABLE: actions
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  excludeDevDependencies: true

functions:
  create:
    name: createActions
    handler: create.create
    events:
      - http:
          path: actions
          method: post
          cors: true

  get:
    name: getActions
    handler: get.get
    events:
      - http:
          path: actions/{name}
          method: get
          cors: true

  list:
    name: listActions
    handler: list.list
    events:
      - http:
          path: actions
          method: get
          cors: true        

  update:
    name: updateActions
    handler: update.update
    events:
      - http:
          path: actions/{name}
          method: put
          cors: true

  delete:
    name: deleteActions
    handler: delete.delete
    events:
      - http:
          path: actions/{name}
          method: delete
          cors: true         

resources:
  Resources:
    ActionsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
          # - AttributeName: maxFrequency
          #   AttributeType: N
          # - AttributeName: frequencyCadence
          #   AttributeType: S
          # - AttributeName: funFact
          #   AttributeType: S
          # - AttributeName: eligiblePoints
          #   AttributeType: N
          # - AttributeName: funFactImageUrl
          #   AttributeType: S
          # - AttributeName: tileIconUrl
          #   AttributeType: S         
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: actions
