service: serverless-backend-adminData

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  deploymentBucket: 
  
  environment:
    ADMIN_DATA_DYNAMODB_TABLE: ${self:service}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ADMIN_DATA_DYNAMODB_TABLE}"

package:
  excludeDevDependencies: true

functions:
  create:
    name: createAdminData
    handler: create.create
    events:
      - http:
          path: adminData
          method: post
          cors: true
          authorizer:
            name: AdminGroupDataAuthorizer
            arn: arn:aws:cognito-idp:us-east-1:745539300020:userpool/us-east-1_Iz6DhxAP7
            identitySource: method.request.header.Authorization
            type: token

  # get:
  #   name: getAdminData
  #   handler: get.get
  #   events:
  #     - http:
  #         path: adminData/{username}
  #         method: get
  #         cors: true

  list:
    name: listAdminData
    handler: list.list
    events:
      - http:
          path: adminData
          method: get
          cors: true
          authorizer:
            name: AdminGroupDataAuthorizer
            arn: arn:aws:cognito-idp:us-east-1:745539300020:userpool/us-east-1_Iz6DhxAP7
            identitySource: method.request.header.Authorization
            type: token        

  # update:
  #   name: updateadminData
  #   handler: update.update
  #   events:
  #     - http:
  #         path: adminData/{name}
  #         method: put
  #         cors: true

  # delete:
  #   name: deleteadminData
  #   handler: delete.delete
  #   events:
  #     - http:
  #         path: adminData/{name}
  #         method: delete
  #         cors: true
