service: serverless-backend-adminData

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  deploymentBucket: 
  
  environment:
    ADMIN_DATA_DYNAMODB_TABLE: ${self:service}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ADMIN_DATA_DYNAMODB_TABLE}"

package:
  excludeDevDependencies: true

functions:
  create:
    name: createAdminData
    handler: create.create
    events:
      - http:
          path: adminData
          method: post
          cors: true

  # get:
  #   name: getAdminData
  #   handler: get.get
  #   events:
  #     - http:
  #         path: adminData/{username}
  #         method: get
  #         cors: true

  list:
    name: listAdminData
    handler: list.list
    events:
      - http:
          path: adminData
          method: get
          cors: true        

  # update:
  #   name: updateadminData
  #   handler: update.update
  #   events:
  #     - http:
  #         path: adminData/{name}
  #         method: put
  #         cors: true

  # delete:
  #   name: deleteadminData
  #   handler: delete.delete
  #   events:
  #     - http:
  #         path: adminData/{name}
  #         method: delete
  #         cors: true         

resources:
  Resources:
    UDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: createdDate
            AttributeType: N        
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: createdDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.ADMIN_DATA_DYNAMODB_TABLE}
