service: serverless-backend-userActions

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  #deploymentBucket: com.serverless.${self:provider.region}.serverless.deploys
  deploymentBucket:

  environment:
    USERACTIONS_DYNAMODB_TABLE: ${self:service}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USERACTIONS_DYNAMODB_TABLE}"

package:
  excludeDevDependencies: true

functions:
  create:
    name: createUserActions
    handler: create.create
    events:
      - http:
          path: userActions
          method: post
          cors: true

  get:
    name: getUserActions
    handler: get.get
    events:
      - http:
          path: userActions/{username}
          method: get
          cors: true

  list:
    name: listUserActions
    handler: list.list
    events:
      - http:
          path: userActions
          method: get
          cors: true        

  # update:
  #   name: updateUserActions
  #   handler: update.update
  #   events:
  #     - http:
  #         path: userActions/{name}
  #         method: put
  #         cors: true

  # delete:
  #   name: deleteUserActions
  #   handler: delete.delete
  #   events:
  #     - http:
  #         path: userActions/{name}
  #         method: delete
  #         cors: true         

resources:
  Resources:
    UDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N         
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USERACTIONS_DYNAMODB_TABLE}
